/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5ad016a6-11ea-4c55-98cf-945c657eb7cb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rTPG6lK7V",
    "aws_user_pools_web_client_id": "3j2iu250p2tltn4ge9qsmad8o7",
    "oauth": {},
    "aws_user_files_s3_bucket": "one-q-raw-form-data231142-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://riyhzvut2nei5kowcailcuae5u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
